# Generated by Django 4.0.5 on 2022-06-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='номенклатура',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.TextField(verbose_name='Название')),
                ('доступность_товара', models.IntegerField(verbose_name='Доступность_товара')),
                ('коментарий', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
            ],
            options={
                'verbose_name': 'Номенклатура ',
                'verbose_name_plural': 'Номенклатуры',
            },
        ),
        migrations.CreateModel(
            name='тип_сыра',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('тип_сыра', models.TextField(null=True, verbose_name='Тип_сыра')),
            ],
        ),
        migrations.CreateModel(
            name='цена',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('еденица_измерения', models.TextField(verbose_name='Еденица_измерения')),
                ('цена_за_единицу', models.IntegerField(verbose_name='Цена за единицу')),
                ('id_номенклатура', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.номенклатура', verbose_name='id_Номенклатура')),
            ],
            options={
                'verbose_name': 'цена ',
                'verbose_name_plural': 'цены',
            },
        ),
        migrations.AddField(
            model_name='номенклатура',
            name='id_тип_сыра',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.тип_сыра', verbose_name='Тип сыра'),
        ),
        migrations.CreateModel(
            name='корзина',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_покупатели', models.IntegerField(blank=True, verbose_name='id_Покупатели')),
                ('объем_покупки', models.IntegerField(verbose_name='Объем покупки')),
                ('Создание', models.DateTimeField(auto_now_add=True, verbose_name='Дата_время_создания')),
                ('Обновление', models.DateTimeField(auto_now=True, verbose_name='Дата_время_обновления')),
                ('id_номенклатура', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.номенклатура', verbose_name='id_Номенклатура')),
            ],
            options={
                'verbose_name': 'корзина ',
                'verbose_name_plural': 'корзины',
            },
        ),
        migrations.CreateModel(
            name='заказы',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_покупатели', models.IntegerField(blank=True, verbose_name='id_Покупатели')),
                ('объем_покупки', models.IntegerField(verbose_name='Объем покупки')),
                ('id_адрес_доставки', models.IntegerField(blank=True, verbose_name='id адрес доставки')),
                ('Создание', models.DateTimeField(auto_now_add=True, verbose_name='Дата_время_создания')),
                ('Обновление', models.DateTimeField(auto_now=True, verbose_name='Дата_время_обновления')),
                ('коментарий', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
                ('доставлен', models.BooleanField(default=False, verbose_name='Состояние доставки')),
                ('id_номенклатура', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.номенклатура', verbose_name='id_Номенклатура')),
            ],
            options={
                'verbose_name': 'заказ ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
