# Generated by Django 4.0.5 on 2022-06-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='тип_сыра',
            options={'verbose_name': 'Тип_сыра ', 'verbose_name_plural': 'Тип_сыров'},
        ),
    ]
